default: &default
  adapter: mysql2
  username: root
  password: 123456
  timeout: 5000

development:
  <<: *default
  database: crowdsale_dev

test:
  <<: *default
  database: crowdsale_test

production:
  <<: *default
  database: crowdsale_prod
